# Generated by Django 3.2.5 on 2021-07-13 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 56, 25, 519132), verbose_name='Fecha de publicación'),
        ),
    ]
