# Generated by Django 3.2.5 on 2021-07-14 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 18, 6, 27, 677645), verbose_name='Fecha de publicación'),
        ),
    ]
