# Generated by Django 3.2.5 on 2021-07-14 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 18, 26, 46, 182884), verbose_name='Fecha de publicación'),
        ),
    ]
