# Generated by Django 3.2.5 on 2021-07-15 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso_contenido',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='curso_titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='curso_publicado',
        ),
        migrations.AddField(
            model_name='curso',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 17, 44, 8, 84451), verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
