# Generated by Django 3.2.5 on 2021-07-15 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210715_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 17, 48, 32, 612010), verbose_name='Fecha de publicación'),
        ),
    ]
