# Generated by Django 3.2.5 on 2021-07-16 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=200)),
                ('fecha_incripcion', models.DateTimeField(default=datetime.datetime(2021, 7, 16, 17, 1, 50, 814425))),
                ('nombre_curso', models.CharField(max_length=50)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
