# Generated by Django 3.2.5 on 2021-07-16 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_incripcion',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
