# Generated by Django 3.2.5 on 2021-07-17 06:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20210717_0120'),
        ('inscripciones', '0002_alter_inscripciones_fecha_incripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_incripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 1, 19, 49, 179401)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
        ),
    ]
