# Generated by Django 3.2.5 on 2021-07-17 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_auto_20210717_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='fecha_incripcion',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 28, 43, 68641)),
        ),
    ]
