# Generated by Django 3.2.5 on 2021-07-17 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_auto_20210717_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 30, 12, 138622)),
        ),
    ]
