# Generated by Django 3.2.5 on 2021-07-17 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_curso_publicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0005_alter_inscripciones_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='user',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
