# Generated by Django 3.2.5 on 2021-07-17 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_auto_20210717_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 16, 29, 13, 891091)),
        ),
    ]
