# Generated by Django 3.2.5 on 2021-07-17 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_alter_inscripciones_fecha_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='fecha_inscripcion',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 16, 47, 14, 207038)),
        ),
    ]
