# Generated by Django 3.2.5 on 2021-07-18 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_auto_20210717_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='apellido_estudiante',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='nombre_estudiante',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 19, 33, 44, 170730)),
        ),
    ]
