# Generated by Django 3.2.5 on 2021-07-18 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_auto_20210717_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='apellido_estudiante',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 19, 36, 7, 960331)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_estudiante',
            field=models.TextField(max_length=20),
        ),
    ]
