# Generated by Django 3.2.5 on 2021-07-18 01:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_curso_publicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0011_auto_20210717_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 20, 54, 14, 393234)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
