# Generated by Django 3.2.5 on 2021-07-18 02:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_curso_publicado'),
        ('inscripciones', '0012_auto_20210717_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 21, 7, 1, 932512)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
        ),
    ]
