# Generated by Django 3.2.5 on 2021-07-18 07:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_curso_publicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0013_auto_20210717_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 2, 41, 40, 35772)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
