# Generated by Django 3.2.5 on 2021-07-18 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0014_auto_20210718_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 13, 21, 51, 532806)),
        ),
    ]
