# Generated by Django 3.2.5 on 2021-07-18 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_curso_publicado'),
        ('inscripciones', '0015_alter_inscripciones_fecha_registro_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 13, 33, 24, 135933)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
        ),
    ]
