# Generated by Django 3.2.5 on 2021-07-18 23:14

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0028_alter_curso_publicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0016_auto_20210718_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 18, 13, 50, 225824)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='nombre_curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
