# Generated by Django 3.2.5 on 2021-07-18 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0017_auto_20210718_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 18, 15, 7, 467616)),
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
