# Generated by Django 3.2.5 on 2021-07-19 05:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0019_auto_20210718_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha_registro_curso',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 0, 22, 55, 463302)),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='usuario',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
